dataset:
  val:
  - name: mytumor
    disp_name: mytumor_val
    image_dir: C:\Users\Boxcat21\Documents\SoftwareWorkspace\Data\MarigoldData\batch1\images 
    depth_dir: C:\Users\Boxcat21\Documents\SoftwareWorkspace\Data\MarigoldData\batch1\depths
    depth_format: image
    image_extension: png
    depth_extension: png
    has_invalid_depth: false
