dataset:  
  train:
    batch_size: 2
    name: tumor_dataset
    type: paired_image_depth
    dir: /mnt/c/Users/Boxcat21/Documents/SoftwareWorkspace/Data/MarigoldData/batch1  # e.g., datasets/mytumor
    filenames: data_split/tumor_depth/filenames_train.txt
    depth_format: image
    image_extension: png
    depth_extension: png
    has_invalid_depth: false
    shuffle: true
    drop_last: true
    infinite: true
